//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_view
    {
        public int AppointID { get; set; }
        public string Name { get; set; }
        public int PatientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
