//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Appointment_Status { get; set; }
        public Nullable<double> Bill_Amount { get; set; }
        public string Bill_Status { get; set; }
        public Nullable<int> DoctorNotification { get; set; }
        public Nullable<int> PatientNotification { get; set; }
        public Nullable<int> FeedbackStatus { get; set; }
        public string Disease { get; set; }
        public string Progress { get; set; }
        public string Prescription { get; set; }
        public Nullable<System.DateTime> AppointmentStart { get; set; }
        public Nullable<System.DateTime> AppointmentEnd { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
