//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosConsulta
    {
        public int PatientID { get; set; }
        public string palergia { get; set; }
        public string palergiadec { get; set; }
        public Nullable<bool> phospre { get; set; }
        public Nullable<bool> pcirpre { get; set; }
        public Nullable<bool> pdia { get; set; }
        public Nullable<bool> penftiro { get; set; }
        public Nullable<bool> phipart { get; set; }
        public Nullable<bool> pcardio { get; set; }
        public Nullable<bool> ptrauma { get; set; }
        public Nullable<bool> pcancer { get; set; }
        public Nullable<bool> ptuber { get; set; }
        public Nullable<bool> ppatores { get; set; }
        public Nullable<bool> ppatogas { get; set; }
        public Nullable<bool> penftrans { get; set; }
        public Nullable<bool> penfrenal { get; set; }
        public Nullable<bool> potrospat { get; set; }
        public Nullable<bool> pactfis { get; set; }
        public Nullable<bool> ptab { get; set; }
        public Nullable<bool> palco { get; set; }
        public Nullable<bool> pdroga { get; set; }
        public Nullable<bool> pvacuna { get; set; }
        public Nullable<bool> potronopat { get; set; }
        public Nullable<bool> pdiaah { get; set; }
        public Nullable<bool> pcardioah { get; set; }
        public Nullable<bool> phipartah { get; set; }
        public Nullable<bool> penftiroah { get; set; }
        public Nullable<bool> penfrenalah { get; set; }
        public Nullable<bool> potroanther { get; set; }
        public string pfpmens { get; set; }
        public string pfumens { get; set; }
        public string pcarmens { get; set; }
        public string pgesta { get; set; }
        public string pp { get; set; }
        public string pc { get; set; }
        public string pa { get; set; }
        public string pile { get; set; }
        public string plcctam { get; set; }
        public string plccsem { get; set; }
        public string psgtam { get; set; }
        public string psgsem { get; set; }
        public string pai { get; set; }
        public string pacienteusg { get; set; }
        public Nullable<bool> pembgine { get; set; }
        public Nullable<bool> pcancer2 { get; set; }
        public Nullable<bool> puter { get; set; }
        public Nullable<bool> pcanma { get; set; }
        public Nullable<bool> pactsex { get; set; }
        public string pmetplani { get; set; }
        public Nullable<bool> pterhormo { get; set; }
        public string pultpapa { get; set; }
        public string pultmasto { get; set; }
        public string potroagine { get; set; }
        public string amiso { get; set; }
        public string tdia { get; set; }
        public string encar { get; set; }
        public string enen { get; set; }
        public string tcan { get; set; }
        public string coag { get; set; }
        public string anemia { get; set; }
        public string trans { get; set; }
        public string cirpre { get; set; }
        public string medact { get; set; }
        public string otroap { get; set; }
        public string grh { get; set; }
        public string ntab { get; set; }
        public string nalco { get; set; }
        public string ndroga { get; set; }
        public string ppeso { get; set; }
        public string ptalla { get; set; }
        public string pta { get; set; }
        public string pfc { get; set; }
        public string pto { get; set; }
        public string pfr { get; set; }
        public string ppep { get; set; }
        public string QuienTuvo { get; set; }
        public string AHFOtros { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
