//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class deptInfo
    {
        public string DeptName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Number_of_Doctors { get; set; }
    }
}
