//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int PatientID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
        public string Teléfono_móvil { get; set; }
        public string Sin_celular { get; set; }
        public string Teléfono { get; set; }
        public string CURP { get; set; }
        public string Dirección { get; set; }
        public string País { get; set; }
        public string Estado { get; set; }
        public string Ciudad { get; set; }
        public string CP { get; set; }
        public string Número_exterior { get; set; }
        public string Número_interior { get; set; }
        public string pacientecurp { get; set; }
        public string pacienteservi { get; set; }
        public string pedociv { get; set; }
        public string pnedu { get; set; }
        public string pocupa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual DatosConsulta DatosConsulta { get; set; }
    }
}
